import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Concatenates the token file and every component stylesheet into the single
 * `dist/styles.css` that package.json actually exports.
 *
 * Why this script exists at all: the normal React pattern of `import
 * './Button.css'` inside Button.tsx makes esbuild emit a *separate*
 * `dist/index.css` that the `exports` map never points at. A consumer doing
 * `import '@sketch-ui/react/styles.css'` then gets the tokens and none of the
 * component rules — silently, with no build error anywhere. Components
 * therefore never import CSS; this script assembles it instead.
 *
 * The file list is discovered rather than hand-maintained, so adding a
 * component can't leave its styles out of the published bundle.
 */

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const srcDir = resolve(root, 'src');
const tokensFile = resolve(srcDir, 'styles.css');

function findStylesheets(dir) {
  const found = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...findStylesheets(path));
    } else if (entry.name.endsWith('.css') && path !== tokensFile) {
      found.push(path);
    }
  }
  return found.sort();
}

const componentFiles = findStylesheets(srcDir);

const chunks = [
  '/* AUTO-GENERATED by scripts/build-css.mjs — edit the source files, not this. */',
  `/* tokens: src/styles.css */`,
  readFileSync(tokensFile, 'utf8'),
  ...componentFiles.flatMap((file) => [
    `/* ${relative(root, file)} */`,
    readFileSync(file, 'utf8'),
  ]),
];

mkdirSync(resolve(root, 'dist'), { recursive: true });
writeFileSync(resolve(root, 'dist/styles.css'), chunks.join('\n'));

console.log(
  `build-css: wrote dist/styles.css (tokens + ${componentFiles.length} component stylesheet${
    componentFiles.length === 1 ? '' : 's'
  })`,
);
